# Generated by Django 5.2.17 on 2026-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=150)),
                ('paciente_telefono', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo_consulta', models.TextField()),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
